/* Presentation based on the user's supplied Pawday HTML. Matching stays unchanged. */
function templateIntro(){
 const examples=[['Cavapoo','left',88],['Pembroke Welsh Corgi','right',85],['Beagle','center',92]];
 return `<section class="template-intro"><div class="template-hero"><span class="eyebrow">${t(L('ТВОЯ ЖИЗНЬ + СОБАКА','YOUR LIFE + A DOG','你的生活 + 狗狗'))}</span><h1>${t(L('Найдём собаку под твою жизнь, а не наоборот','Find a dog for your life, not the other way around','找到适合你生活的狗狗'))}</h1><p>${t(L('Расскажи, как ты живёшь, — и получи подборку пород, с которыми стоит познакомиться.','Tell us how you live and discover dogs worth getting to know.','说说你的生活，认识值得了解的狗狗。'))}</p></div><div class="template-examples"><div class="template-fan" aria-label="${t(L('Пример подборки','Example matches','匹配示例'))}">${examples.map(([name,pos,score])=>{const b=breeds.find(x=>x.latin===name),p=window.pawdayPhotos[name];return `<div class="fan-slot ${pos}"><div class="fan-card"><div class="fan-photo"><img src="${p.src}" alt="${t(b.name)}" width="160" height="120"></div><strong>${t(b.name)}</strong><span class="fan-match">${score}% ${t(L('совпадение','match','匹配'))}</span></div></div>`}).join('')}</div><p class="fan-caption">${t(L('Пример подборки — твоя будет своя','Example matches — yours will be personal','仅为示例，你的结果会不同'))}</p></div><div class="template-consider"><strong>${t(L('Учитываем всё, что важно','We consider what matters','考虑重要的生活条件'))}</strong><div class="template-chips">${[['⌂',L('Жильё','Home','住房')],['♡',L('Дети и питомцы','Kids and pets','孩子及宠物')],['◷',L('Время','Time','时间')],['$',L('Бюджет','Budget','预算')],...(qs.some(q=>q.key==='travel')?[['↗',L('Путешествия','Travel','旅行')]]:[])].map(([icon,label])=>`<span><i aria-hidden="true">${icon}</i>${t(label)}</span>`).join('')}</div><p class="template-meta">${t(L('≈ 5 минут','≈ 5 minutes','约5分钟'))} · ${qs.length} ${t(L('вопросов','questions','个问题'))} · ${breeds.length} ${t(L('профилей собак','dog profiles','个犬只档案'))}</p></div></section>`;
}
let compactPreviousStep=null;
let compactStarted=false;
render=function(){
 if(step<0){compactStarted=false;step=0;}
 document.documentElement.lang=lang==='zh'?'zh-Hans':lang;
 document.getElementById('language').value=lang;
 document.getElementById('prototype').textContent='';
 document.title='Pawday — '+t(ui.tag);
 const skip=document.querySelector('.skip-link');if(skip)skip.textContent=t(L('К вопросам','Skip to questions','跳至问题'));
 if(step===qs.length){renderResults();return;}
 const changed=compactPreviousStep!==step;compactPreviousStep=step;
 const Q=qs[step],count=qs.filter(hasAnswer).length,pct=Math.round(count/qs.length*100);
 app.innerHTML=`<div class="template-page ${step===0&&!compactStarted?'is-opening':''}">${step===0&&!compactStarted?templateIntro():''}<section class="template-question-wrap" id="quiz"><button type="button" class="template-dog mascot-button" data-mascot aria-label="${t(L('Поиграть с собачкой','Play with the puppy','和小狗玩耍'))}" title="${t(L('Нажми — поиграем!','Tap to play!','点击一起玩！'))}"><span class="mascot-sprite" aria-hidden="true"></span></button><div class="template-question ${changed?'question-enter':''}"><div class="template-progress-top"><span>${t(L('Вопрос','Question','问题'))} ${step+1} ${t(L('из','of','/'))} ${qs.length}</span><span>${pct}%</span></div><div class="template-progress" role="progressbar" aria-label="${t(L('Прогресс','Progress','进度'))}" aria-valuenow="${pct}" aria-valuemin="0" aria-valuemax="100"><div style="width:${pct}%"></div></div>${typeof liveCounterMarkup==='function'?liveCounterMarkup(Q):''}<h2 id="question-title" tabindex="-1">${t(Q.title)}</h2>${quizAnswersMarkup(Q)}<details class="template-help"><summary>${t(L('Подсказка','A little help','小提示'))}</summary><p>${t(Q.sub)}</p>${quizExtraHelp(Q)}${Q.longHelp&&t(Q.longHelp)!==t(Q.sub)?`<p>${t(Q.longHelp)}</p>`:''}</details><div class="compact-actions"><button type="button" class="template-next" data-next ${!hasAnswer(Q)?'disabled':''}>${t(step===qs.length-1?ui.results:ui.next)}<span aria-hidden="true">→</span></button>${!hasAnswer(Q)?`<p class="template-hint">${t(L('Выбери вариант, чтобы продолжить','Choose an answer to continue','选择答案后继续'))}</p>`:''}${step>0?`<button type="button" class="template-back" data-back>← ${t(ui.back)}</button>`:''}${qs.every(hasAnswer)?`<button type="button" class="template-back" data-return-results>${t(ui.results)}</button>`:''}</div></div></section><p class="template-footnote">${t(familyHint)}</p></div>`;
 app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.choice),opening=!compactStarted;compactStarted=true;pick(b.dataset.answerKey||Q.key,id);const chosen=app.querySelector(`[data-answer-key="${b.dataset.answerKey||Q.key}"][data-choice="${id}"]`);chosen?.classList?.add('answer-pop');chosen?.focus?.({preventScroll:true});if(opening)window.scrollTo({top:0,behavior:'instant'});});
 if(typeof bindLiveCounter==='function')bindLiveCounter(Q);
 const mascot=app.querySelector('[data-mascot]');if(mascot)mascot.onclick=()=>{mascot.classList.remove('is-playing');void mascot.offsetWidth;mascot.classList.add('is-playing');};
 app.querySelector('[data-next]').onclick=()=>{if(hasAnswer(Q))moveToQuestion(step+1)};
 const back=app.querySelector('[data-back]');if(back)back.onclick=()=>moveToQuestion(step-1);
 const ret=app.querySelector('[data-return-results]');if(ret)ret.onclick=()=>moveToQuestion(qs.length);
};
moveToQuestion=function(next){step=next;render();window.scrollTo({top:0,behavior:'instant'});app.querySelector('#question-title')?.focus?.({preventScroll:true});};
render();
