/* Pawday: playful, family-friendly presentation; matching rules remain in matching.js. */
const chapters=[
 {label:L('Твой дом','Your home','你的家'),keys:['goal','size','home','family','experience'],icon:'🏡',tip:L('Представь ваш обычный день. Какая собака могла бы стать его частью?','Picture an ordinary day. What kind of dog could be part of it?','想象平常的一天，什么样的狗狗能融入其中？')},
 {label:L('Ваш день','Your day','你们的一天'),keys:['alone','walk','activity','training'],icon:'☀️',tip:L('Считаем время всей семьи — даже в самый занятый день.','Think about the whole family’s time, even on a busy day.','想想全家能投入的时间，即使是在忙碌的日子。')},
 {label:L('Забота','Daily care','日常照护'),keys:['leash','noise','care','budget'],icon:'💛',tip:L('У каждой собаки есть свои привычки. Что подойдёт вашей семье?','Every dog has its own habits. What would work for your family?','每只狗都有自己的习惯，哪些适合你们家？')},
 {label:L('Твой друг','Your friend','你的伙伴'),keys:['adoption'],icon:'🐾',tip:L('Осталось немного. Скоро познакомимся с возможными друзьями!','Almost there. Your possible new friends are coming up!','快完成了，即将认识可能适合你的伙伴！')}
];
function chapterIndex(){return Math.max(0,chapters.findIndex(c=>c.keys.includes(qs[step]?.key)));}
const shortQuestions={
 size:[L('Какого размера будет твой друг?','How big would you like your dog?','你希望狗狗多大？'),L('Можно выбрать несколько размеров взрослой собаки.','You can choose several adult sizes.','可以选择多个成年体型。')],
 goal:[L('Какого друга ты ищешь?','What kind of friend are you looking for?','你想找什么样的伙伴？'),L('Для уютных будней, приключений или занятий спортом?','For everyday company, adventures or dog sports?','日常陪伴、探险，还是犬类运动？')],
 home:[L('Где будет жить собака?','Where will your dog live?','狗狗会住在哪里？'),L('Выбери ваш дом. Гулять нужно даже тем, у кого есть двор.','Choose your home. A garden does not replace walks.','选择你们的住所，有院子也需要散步。')],
 family:[L('Кто живёт с тобой?','Who lives with you?','谁和你一起住？'),L('Отметь всех. Если тебе 8–17 лет, отметь и себя.','Choose everyone. If you are 8–17, include yourself.','选择所有成员，如果你8–17岁，也记得选上自己。')],
 experience:[L('У вас уже была собака?','Have you had a dog before?','你们以前养过狗吗？'),L('Учитывай опыт тех, кто будет о ней заботиться.','Think about the people who will care for the dog.','考虑将照顾狗狗的人的经验。')],
 alone:[L('Сколько времени собака будет одна?','How long will your dog be alone?','狗狗会独处多久？'),L('Когда все на работе, в школе или в дороге.','While everyone is at work, school or travelling home.','大家上班、上学或在路上的时候。')],
 walk:[L('Сколько сможете гулять каждый день?','How much walking fits into each day?','每天能散步多久？'),L('Сложи все прогулки за день. Игры дома посчитаем отдельно.','Add up all daily walks. We count indoor games separately.','加起来一天所有散步时间，室内游戏另算。')],
 activity:[L('Что будете делать вместе?','What will you do together?','你们想一起做什么？'),L('Выбирай то, что вам уже нравится. Можно несколько!','Choose things you already enjoy. Pick more than one!','选择你们已经喜欢的活动，可以多选！')],
 training:[L('А сколько времени на игры и обучение?','How much time for games and learning?','游戏和学习能投入多久？'),L('Учить команды, искать игрушки и заниматься вместе.','Learning cues, finding toys and doing things together.','学习指令、找玩具及一起活动。')],
 leash:[L('Как будете гулять?','How will you go on walks?','你们会怎样散步？'),L('Некоторые собаки могут увлечься запахом и убежать.','Some dogs may follow a scent and run off.','有些狗可能循着气味跑远。')],
 noise:[L('А если собака громко лает?','What if your dog barks a lot?','如果狗狗经常吠叫呢？'),L('Подумай о семье и соседях. Обучение не всегда убирает лай.','Think about family and neighbours. Training may not stop all barking.','考虑家人及邻居，训练不一定能消除所有吠叫。')],
 care:[L('Готовы расчёсывать и стричь?','Ready for brushing and haircuts?','愿意梳毛和修剪吗？'),L('Красивой шерсти нужен регулярный уход.','Coats need regular care to stay in good shape.','健康的毛发需要规律护理。')],
 budget:[L('Какой уход вы сможете оплачивать?','What care can your household budget cover?','家庭预算能承担哪些照护？'),L('Корм, ветеринар, уход. Если не знаешь — спроси взрослых.','Food, vet visits and grooming. Not sure? Ask an adult.','食物、兽医及护理。不确定的话，问问大人。')],
 age:[L('Щенок или взрослая собака?','Puppy or grown-up dog?','幼犬还是成年犬？'),L('У взрослой собаки проще заранее узнать привычки.','You can learn more about an adult dog’s habits before bringing them home.','成年犬的习惯通常更容易提前了解。')],
 adoption:[L('Рассмотрим и собак без породы?','Open to mixed-breed dogs too?','也考虑混种犬吗？'),L('Друг может быть породистым, метисом или с неизвестными родителями.','Your friend could be purebred, mixed-breed or have unknown ancestry.','伙伴可以是纯种、混种，或血统未知的狗狗。')],
 favorite:[L('Кто тебе уже нравится?','Already have a favourite?','已经有喜欢的犬种了吗？'),L('Посмотрим и эту породу. Можно выбрать «Пока нет».','We will look at that breed too. “No favourite yet” is fine.','也会查看这个犬种，可以选“暂时没有”。')]
};
qs.splice(qs.findIndex(q=>q.key==='help'),1);
for(const Q of qs){Q.longHelp=Q.sub;[Q.title,Q.sub]=shortQuestions[Q.key];}
const optionCopy={
 goal:[L('Друг для семьи и прогулок','Family friend and walking buddy','家庭及散步伙伴'),L('Партнёр для приключений','Adventure buddy','探险伙伴'),L('Партнёр для задач и спорта','Training and sport partner','任务及运动伙伴'),L('Пока не знаю','Help me choose','帮我选择')],
 leash:[L('Хочу часто отпускать без поводка','Often off lead in open spaces','经常在开放区域脱绳'),L('Поводок и безопасные площадки подходят','Leads and secure spaces work for me','接受牵引及安全场地'),L('Пока не знаю','Not sure yet','暂时不确定')],
 noise:[L('Частый лай нам не подходит','Frequent barking would be a problem','不能接受经常吠叫'),L('Готовы работать над лаем','Ready to work on barking','愿意训练改善吠叫'),L('Строгих ограничений нет','No strict noise limits','无严格噪音限制')],
 care:[L('Минимум ухода за шерстью','Simple coat care','简单毛发护理'),L('Регулярно расчёсывать — да','Regular brushing is fine','可以规律梳毛'),L('Готовы ухаживать каждый день','Ready for daily care and grooming','愿意每日护理及美容')],
 walk:[L('Меньше 30 минут','Under 30 minutes','少于30分钟'),L('30 минут','30 minutes','30分钟'),L('1 час','1 hour','1小时'),L('1,5 часа','1½ hours','1.5小时'),L('2 часа','2 hours','2小时'),L('3 часа и больше','3 hours or more','3小时以上')]
};
for(const [key,labels] of Object.entries(optionCopy))qs.find(q=>q.key===key).options.forEach((o,i)=>o.label=labels[i]);
qs.find(q=>q.key==='walk').options=[o(0,'🚶','30–60 минут','30–60 minutes','30–60分钟'),o(1,'🌳','1–2 часа','1–2 hours','1–2小时'),o(2,'🥾','2–3 часа','2–3 hours','2–3小时'),o(3,'🏞️','Больше 3 часов','Over 3 hours','超过3小时')];
qs.find(q=>q.key==='activity').options=[o(0,'☕','Неспешные прогулки','Gentle walks','悠闲散步'),o(1,'🎾','Игры в парке','Play in the park','公园玩耍'),o(2,'🥾','Походы, бег и спорт','Hiking, running and sports','徒步、跑步和运动')];
qs.find(q=>q.key==='activity').options[2].icon='🥾';
qs.find(q=>q.key==='noise').options=[o(0,'🤫','Частый лай не подходит','Frequent barking is a problem','不能接受频繁吠叫'),o(1,'🔉','Лай не смущает — готовы работать над этим','Barking is okay; we’re ready to work on it','可以接受吠叫，也愿意一起训练')];
qs.find(q=>q.key==='care').options=[o(0,'🧴','Предпочитаю минимум ухода','I prefer minimal coat care','希望尽量简单'),o(1,'🪮','Готовы посвящать время уходу','Ready to make time for coat care','愿意投入时间护理')];
qs.find(q=>q.key==='budget').options=[o(0,'📝','Эконом-вариант','Budget-conscious','经济型'),o(1,'🧾','Есть бюджет на содержание собаки','We have a dog-care budget','有养狗预算'),o(2,'💭','Пока не знаю','Not sure yet','暂时不确定')];
ui.start=L('Найти своего друга','Find my dog friend','寻找狗狗伙伴');
ui.buddy=L('Большая дружба.\nМаленькие шаги.','Big friendship.\nSmall steps.','大大的友谊，\n小小的步骤。');
ui.helper=L('Здесь нет правильных ответов. Выбирай то, что подходит вашей жизни.','No right or wrong answers. Choose what fits your real life.','没有对错之分，请按真实生活选择。');
ui.title=L('Какая собака —\nтвой будущий друг?','Who could be\nyour dog friend?','哪只狗狗可能\n成为你的伙伴？');
ui.lead=L('Расскажи о вашей жизни. Найдём собак, с которыми стоит познакомиться.','Tell us about your life. Meet dogs worth getting to know.','说说你们的生活，认识值得了解的狗狗。');
ui.choose=L('Выбери один вариант','Choose one answer','选择一项');ui.multi=L('Можно выбрать несколько','Choose all that apply','可以多选');
const familyHint=L('Если тебе меньше 18 лет, проходи вместе со взрослым: время, расходы и заботу важно обсудить всей семьёй.','If you are under 18, explore with an adult. Time, costs and care are family decisions.','如果你未满18岁，请与大人一起完成。时间、费用及照护需要全家讨论。');
function welcomeDogs(){
 const names=['Papillon','Golden Retriever','Miniature Poodle','Shetland Sheepdog','Great Dane','Pembroke Welsh Corgi'];
 return `<aside class="dog-gallery" aria-label="${t(L('Знакомься: разные собаки','Meet dogs of different sizes','认识不同体型的狗狗'))}"><div class="gallery-heading"><span>${t(L('МАЛЕНЬКИЕ. БОЛЬШИЕ. ТВОИ?','SMALL. BIG. YOURS?','小小的，大大的，你的伙伴？'))}</span><span aria-hidden="true">✦</span></div><div class="dog-mosaic">${names.map((name,i)=>{const b=breeds.find(b=>b.latin===name),photo=window.pawdayPhotos[name];return `<figure class="mosaic-dog dog-${i}"><img src="${photo.src}" alt="${t(b.name)}" width="320" height="280" ${i>2?'loading="lazy"':''}><figcaption><strong>${t(b.name)}</strong><span>${t(b.size)}</span></figcaption></figure>`}).join('')}</div><div class="gallery-footer"><span aria-hidden="true">♡</span><p>${t(L('Разные характеры. Одна большая дружба.','Different personalities. One big friendship.','不同的性格，一段大大的友谊。'))}</p></div><details class="gallery-credits"><summary>${t(L('Источники фотографий','Photo credits','照片来源'))}</summary>${names.map(name=>`<a href="${window.pawdayPhotos[name].sourcePage}" target="_blank" rel="noopener noreferrer">${t(breeds.find(b=>b.latin===name).name)}</a>`).join(' · ')}</details></aside>`;
}
function side(){return step<0?`<aside class="story-opening"><img src="story-meeting.png" width="1536" height="1024" alt="${t(L('Ребёнок и щенок идут навстречу друг другу','A child and puppy walking toward each other','孩子与小狗向彼此走来'))}"><p>${t(L('Где-то тебя ждёт твой друг. Давай узнаем, какой он.','Your future friend is out there. Let’s discover who they could be.','未来的伙伴正在等你，一起认识它吧。'))}</p></aside>`:'';}
function friendshipFinish(){return `<div class="story-finish"><img src="story-together.png" width="1536" height="1024" alt="${t(L('Ребёнок сидит рядом с собакой, нежно обняв её','A child sitting beside a dog with an arm gently around it','孩子坐在狗狗旁边，温柔地搂着它'))}"><div><span>${t(L('16 ШАГОВ К ДРУЖБЕ','16 STEPS TOWARD FRIENDSHIP','16步，走向友谊'))}</span><p>${t(L('Ваша история только начинается','Your story is just beginning','你们的故事才刚开始'))}</p></div></div>`;}

let previousJourney=0;
function friendshipJourney(){
 const count=qs.filter(hasAnswer).length,ratio=count/qs.length,from=previousJourney;previousJourney=ratio;
 const label=L('Каждый ответ — ближе к знакомству','Every answer brings you closer','每个回答都让你们更近一步');
 return `<div class="friendship-journey" style="--journey:${ratio};--journey-from:${from}" aria-label="${t(label)}"><div class="journey-labels"><span>${t(L('Ты','You','你'))}</span><span>${t(L('Твой будущий друг','Your future friend','你的未来伙伴'))}</span></div><div class="journey-lane"><div class="journey-track"></div><div class="journey-traveller" aria-hidden="true"><span>☺</span></div><span class="journey-heart" aria-hidden="true">♡</span><img class="journey-dog" src="mascot-transparent.png" width="52" height="52" alt="${t(L('Пушистый проводник','Your fluffy guide','毛茸茸的向导'))}"></div><p class="journey-caption" role="status">${t(count===qs.length?L('Все ответы на месте. Пора знакомиться!','All answers in. Time to meet the dogs!','回答完成，去认识狗狗吧！'):label)}</p></div>`;
}
function moveToQuestion(next){step=next;render();window.scrollTo({top:0,behavior:'instant'});app.querySelector('h1')?.focus?.({preventScroll:true});}
function render(){
 document.documentElement.lang=lang==='zh'?'zh-Hans':lang;
 document.getElementById('prototype').textContent=t(L('Найди своего друга','Find your dog friend','寻找你的狗狗伙伴'));
 document.getElementById('language').value=lang;const skip=document.querySelector('.skip-link');if(skip)skip.textContent=t(L('К вопросам','Skip to content','跳至内容'));document.title='Pawday — '+t(ui.tag);
 if(step===qs.length){renderResults();return;}
 if(step<0){app.innerHTML=`<div class="shell welcome-shell">${side()}<section class="work intro fade"><span class="intro-label">${t(L('ТВОЯ ЖИЗНЬ + СОБАКА','YOUR LIFE + A DOG','你的生活 + 狗狗'))}</span><h1 tabindex="-1">${t(ui.title).replace('\n','<br>')}</h1><p class="sub">${t(ui.lead)}</p><div class="facts"><span>◷ ${t(L('Около 5 минут','About 5 minutes','约5分钟'))}</span><span>✦ ${t(L(`${qs.length} коротких вопросов`,`${qs.length} quick questions`,`${qs.length}个简短问题`))}</span></div><button class="primary yellow start-button" data-start>${t(ui.start)} <span aria-hidden="true">↗</span></button><p class="family-hint">${t(familyHint)}</p><details class="intro-info"><summary>${t(L('Что даст этот тест?','What will this quiz tell me?','这个测试能告诉我什么？'))}</summary><p>${t(ui.note)}</p><p>${t(ui.catalogNote)}</p></details></section></div>${welcomeDogs()}`;app.querySelector('[data-start]').onclick=()=>moveToQuestion(0);return;}
 const Q=qs[step],ci=chapterIndex();
 app.innerHTML=`<div class="shell quiz-shell">${side()}<section class="work quiz-work"><div class="topline"><span>${t(L('ШАГ','STEP','步骤'))} ${step+1} <span class="step-total">/ ${qs.length}</span></span><span aria-current="step">${t(chapters[ci].label)}</span></div>${friendshipJourney()}<div class="question-content fade"><h1 tabindex="-1">${t(Q.title)}</h1><p class="sub">${t(Q.sub)}</p><div class="answer-hint">${t(Q.multi?ui.multi:ui.choose)}</div>${Q.key==='favorite'?`<label class="select-label" for="favorite-breed">${t(L('Порода собаки','Dog breed','犬种'))}</label><select id="favorite-breed"><option value="" disabled ${answers.favorite===undefined?'selected':''}>${t(ui.choose)}</option>${Q.options.map(O=>`<option value="${O.id}" ${selected(Q,O.id)?'selected':''}>${t(O.label)}</option>`).join('')}</select>`:`<div class="choices ${Q.options.length>4?'many-options':''} ${['walk','size'].includes(Q.key)?'numeric-options':''}" role="group" aria-label="${t(Q.title)}">${Q.options.map(O=>`<button class="choice ${selected(Q,O.id)?'selected':''}" aria-pressed="${selected(Q,O.id)}" data-choice="${O.id}"><span class="ico" aria-hidden="true">${O.icon}</span><span class="choice-label">${t(O.label)}</span><span class="choice-marker" aria-hidden="true">${selected(Q,O.id)?'✓':'＋'}</span></button>`).join('')}</div>`}<details class="question-help"><summary>${t(L('Подсказка','A little help','小提示'))}</summary><p>${t(Q.longHelp)}</p>${['budget','help','walk'].includes(Q.key)?`<p>${t(familyHint)}</p>`:''}</details></div><div class="bottom"><button class="back" data-back>← ${t(ui.back)}</button><button class="primary" data-next ${!hasAnswer(Q)?'disabled':''}>${t(step===qs.length-1?ui.results:ui.next)} <span aria-hidden="true">→</span></button>${qs.every(hasAnswer)?`<button class="textbutton return-results" data-return-results>${t(ui.results)}</button>`:''}</div></section></div>`;
 if(Q.key==='favorite')app.querySelector('#favorite-breed').onchange=e=>{pick(Q.key,Number(e.target.value));app.querySelector('#favorite-breed')?.focus?.();};
 app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.choice);pick(Q.key,id);app.querySelector(`[data-choice="${id}"]`)?.focus?.({preventScroll:true});});
 const ret=app.querySelector('[data-return-results]');if(ret)ret.onclick=()=>moveToQuestion(qs.length);
 app.querySelector('[data-back]').onclick=()=>moveToQuestion(step-1);
 app.querySelector('[data-next]').onclick=()=>moveToQuestion(step+1);
}
// Visible essentials, with explicitly labelled expandable health and animal guidance.
function profileSummary(b){const e=b.evidence,p=e.resultProfile;return `<section class="profile-summary"><h3>✦ ${t(profileLabels.strengths)}</h3><ul class="strength-list">${p.strengths.map(x=>`<li>${t(x)}</li>`).join('')}</ul><div class="life-fact"><span aria-hidden="true">◷</span><div><strong>${t(profileLabels.lifespan)}</strong><p>${t(p.lifespan.description)}${p.lifespan.sourceUrl?` <a href="${p.lifespan.sourceUrl}" target="_blank" rel="noopener noreferrer">${t(L('Источник','Source','来源'))}</a>`:''}</p></div></div><details class="fact-fold"><summary><span aria-hidden="true">♡</span> ${t(L('Здоровье и забота','Health and care','健康与照护'))}</summary><p>${t(e.health)}</p><p class="footnote">${t(L('Это возможные риски, а не диагноз. Обсуди обследования с ветеринаром.','These are possible risks, not a diagnosis. Discuss screening with a vet.','这些是可能的风险，并非诊断，请与兽医讨论筛查。'))}</p></details><details class="fact-fold"><summary><span aria-hidden="true">⌂</span> ${t(L('С другими животными','Living with other pets','与其他动物生活'))}</summary><h4>${t(profileLabels.dogs)}</h4><p>${t(p.otherDogs)}</p><h4>${t(profileLabels.pets)}</h4><p>${t(p.otherPets)}</p></details><p class="footnote">${t(L('Породные особенности — только ориентир. Познакомьтесь с собакой и обсудите выбор всей семьёй.','Breed traits are a starting point. Meet the dog and discuss the choice as a family.','犬种特点仅作参考，请与狗狗见面并全家讨论选择。'))}</p></section>`;}
render();
